server:
  port: ${SPRING_APPLICATION_PORT:8888}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:config}
#  profiles:
#    active: native
  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
    config:
      server:
        monitor:
          github:
            enabled: true
          gitee:
            enabled: true
        git:
          uri: https://github.com/dqminh2810/PiggyMetricsConfig
          searchPaths: '{application}'

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus