spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#      overrideSystemProperties: false
#      overrideNone: true
#        bootstrap: true
#      enabled: true

server:
  port: ${SPRING_APPLICATION_PORT}
