version: '3.8'
services:
  ###SPRING BOOT###
  gateway:
    build: gateway
    container_name: gateway
    hostname: gateway
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - experience-service
  experience-service:
    build: experience-service
    container_name: experience-service
    hostname: experience-service
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - auth-service
      - account-service
      - notification-service
      - statistic-service
  auth-service:
    build: auth-service
    container_name: auth-service
    hostname: auth-service
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - auth-mongodb
  account-service:
    build: account-service
    container_name: account-service
    hostname: account-service
    restart: always
    ports:
      - 8081:8081
    links:
      - account-mongodb
    depends_on:
      - auth-service
      - account-mongodb
  notification-service:
    build: notification-service
    container_name: notification-service
    hostname: server
    restart: always
    ports:
      - 8082:8082
    links:
      - notification-mongodb
    depends_on:
      - auth-service
      - notification-mongodb
  statistic-service:
    build: statistic-service
    container_name: statistic-service
    hostname: statistic-service
    restart: always
    ports:
      - 8083:8083
    links:
      - statistic-mongodb
    depends_on:
      - auth-service
      - statistic-mongodb

  ###MONGODB###
  notification-mongodb:
    image: mongo:3
    container_name: notification-mongodb
    hostname: notification-mongodb
    restart: unless-stopped
#    ports:
#      - 25000:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  account-mongodb:
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    container_name: account-mongodb
    hostname: account-mongodb
    restart: unless-stopped
#    ports:
#      - 26000:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - INIT_DUMP=${INIT_DUMP_OAUTH2}
  statistic-mongodb:
    image: mongo:3
    container_name: statistic-mongodb
    hostname: statistic-mongodb
    restart: unless-stopped
#    ports:
#      - 27000:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  auth-mongodb:
    image: mongo:3
    container_name: auth-mongodb
    hostname: auth-mongodb
    restart: unless-stopped
#    ports:
#      - 28000:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

