version: '2.1'
services:
  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017
  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017
  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  gateway:
    build: gateway
    ports:
      - 8000:8000

  auth-service:
    build: auth-service
    ports:
      - 9000:9000

  account-service:
    build: account-service
    ports:
      - 8081:8081

  notification-service:
    build: notification-service
    ports:
      - 8082:8082

  statistics-service:
    build: statistics-service
    ports:
      - 8083:8083