scrape_configs:
  - job_name: 'hello-world-piggy-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth-service:9000', 'account-service:8081', 'notification-service:8082', 'statistic-service:8083', 'experience-service:8080', 'gateway:8000']
    basic_auth:
      username: 'user'
      password: 'password'