spring:
  data:
    mongodb:
#      host: localhost
      host: statistic-mongodb
#      host: host.docker.internal
#      port: 27000
      port: 27017
      username: user
      password: password
      database: piggymetrics
server:
  port: 8083
